<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var Template $block */
/** @var FormatterViewModel $formatterViewModel */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$formatterViewModel = $viewModels->require(FormatterViewModel::class);
$segment = $block->getSegment();

?>
<script>
    window.mysegment = <?= json_encode($segment)?>;
</script>
<div class="flex gap-4 justify-between md:gap-0">
    <span class="label">
        Shipping Protection
    </span>
    <span class="value">
        <?= /* @noEscape */ $formatterViewModel->currency($segment['value'] ?? 0) ?>
    </span>
</div>



<!--
  ~ Copyright Extend (c) 2022. All rights reserved.
  ~ See Extend-COPYING.txt for license details.
  -->
<!-- ko if: isDisplayed() -->
<!--<tr class="totals shipping-protection excl">-->
<!--    <th data-bind="text: title" class="mark" scope="row"></th>-->
<!--    <td class="amount">-->
<!--        <span class="price" data-bind="text: getShippingProtectionTotal(), attr: {'data-th': title}"></span>-->
<!--    </td>-->
<!--</tr>-->
<!-- /ko -->

