<?php

    /** @var Magento\Framework\Escaper $escaper */
    /** @var Magento\Catalog\Block\Product\View $block */
    $viewModel = $block->getData('viewModel');
    $extendSdk = 'https://sdk.helloextend.com/extend-sdk-client/v1/extend-sdk-client.min.js';
    $extendMagentoSdk = 'https://sdk.helloextend.com/extend-sdk-client-magento-addon/v1/extend-sdk-client-magento-addon.min.js';
    $cartUtils = $escaper->escapeJs($block->getViewFileUrl('Extend_HyvaIntegration::js/utils/cart-utils.js'));
    $stringUtils = $escaper->escapeJs($block->getViewFileUrl('Extend_HyvaIntegration::js/utils/string-utils.js'));

    $isCurrencySupported = $viewModel->isCurrencySupported();
    $shouldRender = $viewModel->isExtendProductProtectionEnabled()
                    && $viewModel->isProductProtectionProductDisplayPageOfferEnabled()
                    && $isCurrencySupported;

?>
<?php if ($shouldRender) : ?>
<script>
    'use strict';
    window.addEventListener('load', () => {
        initExtendBase();
    })


    function initExtendBase(){
        const jsFiles = [
            '<?= $cartUtils ?>',
            '<?= $stringUtils ?>'
        ];

        const sdkFiles = {
            extend: {
                src: '<?= $extendSdk ?>'
            },
            magento: {
                src: '<?= $extendMagentoSdk ?>'
            }
        };

        jsFiles.forEach((item) => {
            let script = document.createElement('script');
            script.src = item;
            script.type = 'module';
            document.head.appendChild(script);
        });

        for (let sdk in sdkFiles){
            let script = document.createElement('script');
            script.src = sdkFiles[sdk].src;
            sdkFiles[sdk].script = script;
        }

        sdkFiles.extend.script.addEventListener('load', () => {
            //load sdk config
            const config = [{
                extendStoreUuid: "<?= $block->getData('viewModel')->getExtendStoreUuid() ?>",
                activeEnvironment: "<?= $block->getData('viewModel')->getActiveEnvironment() ?>",
                currencyCode: "<?= $block->getData('viewModel')->getCurrencyCode(); ?>",
            }]

            Extend.config({
                storeId: config[0].extendStoreUuid,
                environment: config[0].activeEnvironment,
                currency: config[0].currencyCode
            });

            document.head.appendChild(sdkFiles.magento.script);

        });

        sdkFiles.magento.script.addEventListener('load', () => { window.dispatchEvent(new Event('extendLoaded')); });

        document.head.appendChild(sdkFiles.extend.script);

    }

</script>
<?php endif; ?>
